# Generated by Django 5.2.6 on 2025-09-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_registration_mode_of_learning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mode_of_learning',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('virtual', 'Virtual')], max_length=10),
        ),
    ]
