# Generated by Django 5.2.6 on 2025-09-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_alter_registration_mode_of_learning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('partial', 'partial'), ('completed', 'Completed')], max_length=20),
        ),
    ]
