# Generated by Django 5.2.6 on 2025-09-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_alter_registration_payment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mode_of_learning',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('partial', 'Partial'), ('completed', 'Completed')], max_length=20),
        ),
    ]
