# Generated by Django 5.2.6 on 2025-09-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_alter_registration_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mode_of_learning',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('virtual', 'Virtual')], max_length=10),
        ),
    ]
